# Generated by Django 5.1.2 on 2025-06-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='RoleMaster',
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
